language: node_js
node_js:
- "10"
- "8"
script:
- npm run test:e2e
- npm run test:unit
- npm run lint
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - oracle-java8-set-default
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start" # the starting the virtual X frame buffer: Xvfb process
- sleep 3 #wait a while before xvfb to start
after_script:
- "sh -e /etc/init.d/xvfb stop"
